export const Transactions = [
  {
    customerId: "100",
    fullName: "Mike",
    email: "mike@abc.com",
    status: "Gold",
    contactNo: "4252452452",
    transactions: [
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 700,
        points: "",
        month: "Jan",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 300,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 120,
        points: "",
        month: "Mar",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Router",
        price: 7000,
        points: "",
        month: "Jan",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Cable",
        price: 300,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Modem",
        price: 120,
        points: "",
        month: "March",
      },
    ],
  },
  {
    customerId: "101",
    fullName: "Jhon",
    email: "jhon@abc.com",
    status: "Gold",
    contactNo: "4258852452",
    transactions: [
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 500,
        points: "",
        month: "Jan",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 800,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 350,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Router",
        price: 5000,
        points: "",
        month: "Jan",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Cable",
        price: 3020,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Modem",
        price: 1200,
        points: "",
        month: "Mar",
      },
    ],
  },
  {
    customerId: "103",
    fullName: "Maxi",
    email: "maxi@abc.com",
    status: "Silver",
    contactNo: "4252452662",
    transactions: [
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 400,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 150,
        points: "",
        month: "Mar",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "abc",
        price: 90,
        points: "",
        month: "Mar",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Router",
        price: 1000,
        points: "",
        month: "Jan",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Cable",
        price: 3720,
        points: "",
        month: "Feb",
      },
      {
        transationId: Math.floor(Math.random() * 1000000),
        item: "Modem",
        price: 1250,
        points: "",
        month: "March",
      },
    ],
  },
];
